### ISSUE TITLE
Implement addition of arbitrary EVE-JSON fields.

### ISSUE THREAD

**Issue by satta** [DCSO/fever#49]
I propose to add a configuration setting that allows to set additional fields in the EVE-JSON items. This could be used, for example, to add sensor IDs:

```yaml
extra-fields:
  - name: sensor_id
    value: foobarbaz
```
