### ISSUE TITLE
Allow multiple Stenosis backends for multiple input interfaces

### ISSUE THREAD

**Issue by satta** [DCSO/fever#59]
For multi-interface sensor deployments, it might be useful to selectively send queries for specific interfaces to separate Stenosis hosts, e.g. via the `in_iface` EVE field. This should be configurable in the FEVER YAML config file:

```yaml
stenosis:
  enable: false
  # this would then be commented out in the case of multiple interfaces
  #submission-url: localhost:19205
  submission-timeout: 5s
  # Set to true and parameters below to enable TLS connection to Stenosis
  tls: false
  client-chain-file: client.crt
  client-key-file: client.key
  root-cas:
      - root.crt
  skipverify: false
  interfaces:
    enp94s0f0:
      submission-url: stenosis1.local:19205
    enp94s0f1:
      submission-url: stenosis2.local:19205
```
Alerts coming from interfaces not listed in the configuration should never be used as a basis for Stenosis queries.
